### ISSUE TITLE
Think about crashing the app instead of silently logging errors

### ISSUE THREAD

**Issue by defuse** [zcash/zcash-ios-wallet#112]
There is some code in the app that appears to silently logs errors, e.g.

CombineSynchronizer start():
```
        do {
            if retry {
                stop()
            }
            try synchronizer.start(retry: retry)
        } catch {
            logger.error("error starting \(error)")
        }
```

and perhaps (in SendFlowEnvironment.swift):

```
    func send() {
        guard !txSent else {
            logger.error("attempt to send tx twice")
            return
        }
```

Wherever these are things that *should never happen*, we should crash the app or show an error to the user. This way very rare bugs can't hide from us in logs on the devices of users' who will never ever look at the logs.

**Comment by pacu** [comment]
previously fixed in another issue 
```
func start(retry: Bool = false){
        
        do {
            if retry {
                stop()
            }
            try synchronizer.start(retry: retry)
        } catch {
            logger.error("error starting \(error)")
            self.errorPublisher.send(error)
        }
    }
```

**Comment by defuse** [comment]
Is `errorPublisher` the remote logging or something that will show an error in the UI? Given #102, a "production" release (without the logging) should still show an error that's visible to the user.

**Comment by pacu** [comment]
the error publisher surfaces errors to the user.

**Comment by defuse** [comment]
Excellent thanks!
